arglist; prompt; exargs;

diff --git a/exesh b/exesh
--- a/exesh
+++ b/exesh
@@ -1,14 +1,32 @@
 #!/bin/bash
 
+isurl=false
+nosave=false
+noconf=false
+update=false
+
 if [ $# -eq 0 ]; then
-  echo "Usage: exesh [options] FILE || \"URL\""
+  echo "Usage: exesh [arglist: -nsu] FILE || \"URL\""
   echo "Options:"
-  echo "  -n, --no-save: dont keep the downloaded file after execution"
-  echo "  -u, --update: update exesh"
+  echo "  -n: dont keep the downloaded file after execution"
+  echo "  -y: execute from web without confirmation prompt"
+  echo "  -u: update exesh"
   exit 1
 fi
 
-if [ "$1" == "-u" ] || [ "$1" == "--update" ]; then
+if [ $# -ge 2 ]; then
+  if [[ "$1" == *"n"* ]]; then
+    nosave=true
+  fi
+  if [[ "$1" == *"y"* ]]; then
+    noconf=true
+  fi
+  if [[ "$1" == *"u"* ]]; then
+    update=true
+  fi
+fi
+
+if [[ "$update" = true ]]; then
   echo "Updating exesh..."
   echo "Fetching from github..."
   sudo curl -SL https://raw.githubusercontent.com/Raais/exesh/main/exesh -o /usr/local/bin/exesh
@@ -20,11 +38,10 @@ fi
 if [ $# -eq 1 ]; then
   FILE=$1
 fi
-if [ $# -eq 2 ]; then
+if [ $# -ge 2 ]; then
   FILE=$2
 fi
 
-isurl=false
 URL=${FILE}
 
 if [[ $FILE == http* ]]; then
@@ -53,10 +70,27 @@ if [ ! -x $FILE ]; then
   chmod +x $FILE
 fi
 
-bash $FILE
+RED='\033[0;31m'
+NC='\033[0m'
+
+if [[ "$noconf" = false ]] && [[ "$isurl" = true ]]; then
+  echo -e "${RED}Executing files from the web can be dangerous, are you sure you want to do this?${NC}"
+  read -p "'Y/y' to continue: " -r
+  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+    echo "Aborting..."
+    rm $FILE
+    exit 1
+  fi
+fi
+
+if [ $# -gt 2 ]; then
+  EXARGS=${@:3}
+fi
+
+bash $FILE $EXARGS
 
 if [ $# -eq 2 ] && [[ "$isurl" = true ]]; then
-  if [[ $1 == "-n" || $1 == "--no-save" ]]; then
+  if [[ "$nosave" = true ]]; then
     rm $FILE
   fi
 fi
